name: raygun4flutter
description: Flutter crash reporting provider for Raygun.
version: 0.1.0
homepage: https://raygun.com
repository: https://github.com/MindscapeHQ/Raygun4Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.raygun.raygun4flutter.raygun4flutter
        pluginClass: Raygun4flutterPlugin
      ios:
        pluginClass: Raygun4flutterPlugin
